"""fix cascade settings

Revision ID: 0f8f09165d59
Revises: 13c043c78cfe
Create Date: 2024-07-28 15:45:33.121903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8f09165d59'
down_revision: Union[str, None] = '13c043c78cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_author_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'account', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_author_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'account', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_author_id_fkey', 'review', 'account', ['author_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_author_id_fkey', 'comment', 'account', ['author_id'], ['id'])
    # ### end Alembic commands ###
