"""fix cascade settings

Revision ID: 13c043c78cfe
Revises: 8d70d5da8b23
Create Date: 2024-07-28 14:24:07.838814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c043c78cfe'
down_revision: Union[str, None] = '8d70d5da8b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_review_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_review_id_fkey', 'comment', 'review', ['review_id'], ['id'])
    # ### end Alembic commands ###
