"""add follow

Revision ID: 5f7c152a8a29
Revises: 3e9cff3625ad
Create Date: 2024-07-23 20:51:35.451974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7c152a8a29'
down_revision: Union[str, None] = '3e9cff3625ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_table',
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('follwed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower'], ['account.id'], ),
    sa.ForeignKeyConstraint(['follwed'], ['account.id'], ),
    sa.PrimaryKeyConstraint('follower', 'follwed')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_table')
    # ### end Alembic commands ###
