"""add cascade settings

Revision ID: 8d70d5da8b23
Revises: 6f6629bb49f2
Create Date: 2024-07-28 14:13:40.125480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d70d5da8b23'
down_revision: Union[str, None] = '6f6629bb49f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dislike_comment_table_dislike_comment_fkey', 'dislike_comment_table', type_='foreignkey')
    op.drop_constraint('dislike_comment_table_dislike_comment_account_fkey', 'dislike_comment_table', type_='foreignkey')
    op.create_foreign_key(None, 'dislike_comment_table', 'account', ['dislike_comment_account'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dislike_comment_table', 'comment', ['dislike_comment'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dislike_review_table_dislike_review_fkey', 'dislike_review_table', type_='foreignkey')
    op.drop_constraint('dislike_review_table_dislike_review_account_fkey', 'dislike_review_table', type_='foreignkey')
    op.create_foreign_key(None, 'dislike_review_table', 'review', ['dislike_review'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dislike_review_table', 'account', ['dislike_review_account'], ['id'], ondelete='CASCADE')
    op.drop_constraint('follow_table_follower_id_fkey', 'follow_table', type_='foreignkey')
    op.drop_constraint('follow_table_followed_id_fkey', 'follow_table', type_='foreignkey')
    op.create_foreign_key(None, 'follow_table', 'account', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow_table', 'account', ['followed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('like_comment_table_like_comment_account_fkey', 'like_comment_table', type_='foreignkey')
    op.drop_constraint('like_comment_table_like_comment_fkey', 'like_comment_table', type_='foreignkey')
    op.create_foreign_key(None, 'like_comment_table', 'account', ['like_comment_account'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like_comment_table', 'comment', ['like_comment'], ['id'], ondelete='CASCADE')
    op.drop_constraint('like_review_table_like_review_fkey', 'like_review_table', type_='foreignkey')
    op.drop_constraint('like_review_table_like_review_account_fkey', 'like_review_table', type_='foreignkey')
    op.create_foreign_key(None, 'like_review_table', 'account', ['like_review_account'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like_review_table', 'review', ['like_review'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like_review_table', type_='foreignkey')
    op.drop_constraint(None, 'like_review_table', type_='foreignkey')
    op.create_foreign_key('like_review_table_like_review_account_fkey', 'like_review_table', 'account', ['like_review_account'], ['id'])
    op.create_foreign_key('like_review_table_like_review_fkey', 'like_review_table', 'review', ['like_review'], ['id'])
    op.drop_constraint(None, 'like_comment_table', type_='foreignkey')
    op.drop_constraint(None, 'like_comment_table', type_='foreignkey')
    op.create_foreign_key('like_comment_table_like_comment_fkey', 'like_comment_table', 'comment', ['like_comment'], ['id'])
    op.create_foreign_key('like_comment_table_like_comment_account_fkey', 'like_comment_table', 'account', ['like_comment_account'], ['id'])
    op.drop_constraint(None, 'follow_table', type_='foreignkey')
    op.drop_constraint(None, 'follow_table', type_='foreignkey')
    op.create_foreign_key('follow_table_followed_id_fkey', 'follow_table', 'account', ['followed_id'], ['id'])
    op.create_foreign_key('follow_table_follower_id_fkey', 'follow_table', 'account', ['follower_id'], ['id'])
    op.drop_constraint(None, 'dislike_review_table', type_='foreignkey')
    op.drop_constraint(None, 'dislike_review_table', type_='foreignkey')
    op.create_foreign_key('dislike_review_table_dislike_review_account_fkey', 'dislike_review_table', 'account', ['dislike_review_account'], ['id'])
    op.create_foreign_key('dislike_review_table_dislike_review_fkey', 'dislike_review_table', 'review', ['dislike_review'], ['id'])
    op.drop_constraint(None, 'dislike_comment_table', type_='foreignkey')
    op.drop_constraint(None, 'dislike_comment_table', type_='foreignkey')
    op.create_foreign_key('dislike_comment_table_dislike_comment_account_fkey', 'dislike_comment_table', 'account', ['dislike_comment_account'], ['id'])
    op.create_foreign_key('dislike_comment_table_dislike_comment_fkey', 'dislike_comment_table', 'comment', ['dislike_comment'], ['id'])
    # ### end Alembic commands ###
