"""add fields

Revision ID: ad2988cef79b
Revises: 288f0f270539
Create Date: 2024-07-24 20:26:42.181699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2988cef79b'
down_revision: Union[str, None] = '288f0f270539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('account', sa.Column('summary', sa.String(length=300), nullable=False))
    op.add_column('account', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('account', sa.Column('last_visit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'last_visit')
    op.drop_column('account', 'created_at')
    op.drop_column('account', 'summary')
    op.drop_column('account', 'birthday')
    # ### end Alembic commands ###
