"""fix follow

Revision ID: ff77526ddc8a
Revises: 5f7c152a8a29
Create Date: 2024-07-23 21:30:07.253783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff77526ddc8a'
down_revision: Union[str, None] = '5f7c152a8a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_table', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.add_column('follow_table', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.drop_constraint('follow_table_follwed_fkey', 'follow_table', type_='foreignkey')
    op.drop_constraint('follow_table_follower_fkey', 'follow_table', type_='foreignkey')
    op.create_foreign_key(None, 'follow_table', 'account', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follow_table', 'account', ['followed_id'], ['id'])
    op.drop_column('follow_table', 'follower')
    op.drop_column('follow_table', 'follwed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_table', sa.Column('follwed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follow_table', sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follow_table', type_='foreignkey')
    op.drop_constraint(None, 'follow_table', type_='foreignkey')
    op.create_foreign_key('follow_table_follower_fkey', 'follow_table', 'account', ['follower'], ['id'])
    op.create_foreign_key('follow_table_follwed_fkey', 'follow_table', 'account', ['follwed'], ['id'])
    op.drop_column('follow_table', 'followed_id')
    op.drop_column('follow_table', 'follower_id')
    # ### end Alembic commands ###
