"""add like, dislike

Revision ID: 83c2274071c8
Revises: f8cba5ff4a26
Create Date: 2024-07-22 11:36:19.791303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c2274071c8'
down_revision: Union[str, None] = 'f8cba5ff4a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike_review_table',
    sa.Column('dislike_review_account', sa.Integer(), nullable=False),
    sa.Column('dislike_review', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dislike_review'], ['review.id'], ),
    sa.ForeignKeyConstraint(['dislike_review_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('dislike_review_account', 'dislike_review')
    )
    op.create_table('like_review_table',
    sa.Column('like_review_account', sa.Integer(), nullable=False),
    sa.Column('like_review', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_review'], ['review.id'], ),
    sa.ForeignKeyConstraint(['like_review_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('like_review_account', 'like_review')
    )
    op.create_table('dislike_comment_table',
    sa.Column('dislike_comment_account', sa.Integer(), nullable=False),
    sa.Column('dislike_comment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dislike_comment'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['dislike_comment_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('dislike_comment_account', 'dislike_comment')
    )
    op.create_table('like_comment_table',
    sa.Column('like_comment_account', sa.Integer(), nullable=False),
    sa.Column('like_comment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_comment'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['like_comment_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('like_comment_account', 'like_comment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_comment_table')
    op.drop_table('dislike_comment_table')
    op.drop_table('like_review_table')
    op.drop_table('dislike_review_table')
    # ### end Alembic commands ###
