"""update model 'review'

Revision ID: d69eb3e51390
Revises: 9cc9a39955e6
Create Date: 2024-07-17 10:37:29.901829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69eb3e51390'
down_revision: Union[str, None] = '9cc9a39955e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('review', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'updated_at')
    op.drop_column('review', 'created_at')
    # ### end Alembic commands ###
